language: rust
sudo: false
rust: stable
dist: trusty

matrix:
  include:
    - rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl DEPLOY=1
      before_script:
        - rustup target add $TARGET
        - curl https://www.openssl.org/source/openssl-1.0.2l.tar.gz | tar xzf -
        - (cd openssl-1.0.2l &&
          CC=musl-gcc ./Configure --prefix=$HOME/openssl-musl no-dso no-ssl2 no-ssl3 linux-x86_64 -fPIC &&
          make -j$(nproc) &&
          make install)
        - export OPENSSL_DIR=$HOME/openssl-musl
      script: cargo build --release --target $TARGET --locked

    - os: osx
    - os: osx
      env: MACOSX_DEPLOYMENT_TARGET=10.7 DEPLOY=1 TARGET=x86_64-apple-darwin OPENSSL_STATIC=1
      script: cargo build --release --target $TARGET --locked

addons:
  apt:
    packages:
    - musl-tools

script:
  - cargo test --locked

notifications:
  email:
    on_success: never

before_deploy:
  - name="cargo-vendor-$TRAVIS_TAG-$TARGET"
  - depsname="cargo-vendor-$TRAVIS_TAG-src+deps"
  - mkdir $name
  - cp target/$TARGET/release/cargo-vendor $name/
  - cp README.md LICENSE-MIT LICENSE-APACHE $name/
  - tar czvf $name.tar.gz $name
  - mkdir $depsname
  - git archive HEAD | tar -x -C $depsname
  - PATH="./target/$TARGET/release:$PATH" cargo vendor
  - mv vendor $depsname/
  - tar czvf $depsname.tar.gz $depsname

deploy:
  api_key:
    secure: PUmB2UTZZpIC+hFHqO8lx38R2EkmEIExo/1LnaxffDT1dByASgAwVmnCAb/7G3vdjWpskhu3yj1814g2SaEm79lgdIvFGBEgUkiZy/kzdpNvIdpXKMiFLWluyDyYne7ucDgZfbpn1NgmNXQag7Frq61MF4wDI6KNQSdtVB4WzDv2M4Jm3MfMB0BpWMY4feIHZZRZjS1Kz9FWLsn+h+fTTZFYdSDQRpqFuP3KmesOSy2yaLsiOaZsLkiKIiyqO0/8Ab4/eyIbJNrLJ2ueLmIgKHhVge1a1IULtj/Ffa3vfFz47t92iImF8ZBvGtxdztjBw1/IhFkhW+14YhPir24blIBnru3vYddc69dnXYf20mZhSLvFperBH1iYfQ1lILn/oF+Jg1RSvMQpuLN+NVG2PmDX9HODnjO9wP6L0kyaPbV6/yzLh9wCLOC2Lk4IXcHt7Mn4bzjCwofp8z/NDUWDvdxSLoTaL+q+wXH98XYXWBAgt8QTDrGxmFltsSsjeI1Sl9RMx4OHOWxV6kde13dQ+SNdn5p0vEJVw5CRMOchmJo+8ukbAvlAWP3hiXJiAOAQA177AmcPG9o2d1EpvWEblzRDzVuCp+DPxxWmI1pXZEnWXoAOsma9nhrlJfnSF8c5qfCaAIMEMXO0kNfe8aee+1bsCLRPY51wBda8da7VlFg=
  file_glob: true
  file:
    - cargo-vendor-$TRAVIS_TAG-$TARGET.tar.gz
    - cargo-vendor-$TRAVIS_TAG-src+deps.tar.gz
  on:
    condition: $DEPLOY = 1
    tags: true
  provider: releases
  skip_cleanup: true
